= Utilities

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/community-contracts/utils

Miscellaneous contracts and libraries containing utility functions you can use to improve security, work with new data types, or safely use low-level primitives.

 * {AbstractSigner}: Abstract contract for internal signature validation in smart contracts.
 * {ERC7739}: An abstract contract to validate signatures following the rehashing scheme from `ERC7739Utils`.
 * {ERC7739Utils}: Utilities library that implements a defensive rehashing mechanism to prevent replayability of smart contract signatures based on ERC-7739.
 * {ERC7913Utils}: utilities library that implements ERC-7913 signature verification with fallback to ERC-1271 and ECDSA.
 * {SignerECDSA}, {SignerP256}, {SignerRSA}: Implementations of an {AbstractSigner} with specific signature validation algorithms.
 * {SignerERC7702}: Implementation of {AbstractSigner} that validates signatures using the contract's own address as the signer, useful for delegated accounts following EIP-7702.
 * {SignerERC7913}, {MultiSignerERC7913}, {MultiSignerERC7913Weighted}: Implementations of {AbstractSigner} that validate signatures based on ERC-7913. Including a simple and weighted multisignature scheme.
 * {ERC7913SignatureVerifierP256}, {ERC7913SignatureVerifierRSA}, {ERC7913SignatureVerifierZKEmail}: Ready to use ERC-7913 signature verifiers for P256, RSA keys, and ZKEmail.
 * {SignerZKEmail}: Implementation of an {AbstractSigner} that enables email-based authentication through zero-knowledge proofs.
 * {ZKEmailUtils}: Library for ZKEmail signature validation utilities, enabling email-based authentication through zero-knowledge proofs.
 * {EnumerableSetExtended} and {EnumerableMapExtended}: Extensions of the `EnumerableSet` and `EnumerableMap` libraries with more types, including non-value types.
 * {Masks}: Library to handle `bytes32` masks.

== Cryptography

{{ERC7739}}

{{ERC7739Utils}}

{{ZKEmailUtils}}

=== Abstract Signers

{{AbstractSigner}}

{{SignerECDSA}}

{{SignerERC7913}}

{{MultiSignerERC7913}}

{{MultiSignerERC7913Weighted}}

{{SignerP256}}

{{SignerERC7702}}

{{SignerRSA}}

{{SignerZKEmail}}

=== ERC-7913

{{ERC7913Utils}}

{{ERC7913P256Verifier}}

{{ERC7913RSAVerifier}}

{{ERC7913SignatureVerifierZKEmail}}

== Structs

{{EnumerableSetExtended}}

{{EnumerableMapExtended}}

== Libraries

{{Masks}}
